language: ruby
services:
  - elasticsearch
rvm:
  - "2.1.5"
before_install:
  - gem update --system
  - gem --version
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.1.deb && sudo dpkg -i elasticsearch-1.7.1.deb && sudo service elasticsearch restart
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake test
  - bundle exec rake spec
