language: ruby
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
services:
  - elasticsearch
rvm:
  - "2.1.5"
before_install:
  - gem update --system
  - gem --version
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake test
  - bundle exec rake spec
