oauth2:
  provider:
    shibboleth:
      enabled: true
      key: next
      secret: txen
      properties:
        site: http://localhost
        authorize_url: /shib-oauth2-bridge/public/oauth2/authorize
        token_url: /shib-oauth2-bridge/public/oauth2/access_token
      routes:
        get_user: /shib-oauth2-bridge/public/oauth2/user